micronaut:
  application:
    name: cineminhaTroubleshooting
datasources:
  default:
    url: jdbc:postgresql://localhost:5433/cineminhas
    driverClassName: org.postgresql.Driver
    username: postgres
    password: '1234567'
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: 'create-drop'
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true
